---
- hosts: all
  gather_facts: no
  vars_prompt:
    - name: "shelfish_tag"
      prompt: "Shelfish image tag"
      private: no

  tasks:
    - set_fact: shelfish_tag={{ shelfish_tag }}
      tags: always

- hosts: webservers
  gather_facts: no

  tasks:
    - name: download image
      docker_image:
        name: "freetonik/shelfish:{{ shelfish_tag }}"
        force: yes

    - name: run migrations
      docker_container:
        recreate: yes
        name: shelfish-migrations
        command: "bin/rails db:migrate"
        image: "freetonik/shelfish:{{ shelfish_tag }}"
        state: started
        env_file: "{{ shelfish_env_file }}"
        # env:
        #   MIX_ENV: prod
        volumes:
          - "/tmp:/tmp"
          - "/var/tmp:/var/tmp"
      run_once: yes
      tags: [webserver]

    - name: start application
      docker_container:
        recreate: yes
        name: shelfish-web
        command: "bin/rails server -e production"
        image: "freetonik/shelfish:{{ shelfish_tag }}"
        state: started
        restart_policy: always
        env_file: "{{ shelfish_env_file }}"
        ports:
          - "80:3000"
        volumes:
          # - "/var/run/docker.sock:/var/run/docker.sock"
          - "/tmp:/tmp"
      tags: [webserver]
